### ISSUE TITLE
bundle exec jekyll serve : Not Installed : No such file or directory - git

### ISSUE THREAD

**Issue by GohEeEn** [github/personal-website#134]
![image](https://user-images.githubusercontent.com/34720382/57737536-eda0dc80-76a3-11e9-9800-ce38e864cd17.png)

I am facing this problem while I run the command **bundle exec jekyll serve** on my Window 10 Home machine right after forking this repository, and no modification was done on the source code. All I do was following the instructions given on *Install in your local development environment* section. I am currently using version of **jekyll-3.8.5** and **bundler-2.0.1.** while executing the command.

Does anyone face this problem before ? If yes is that some data or key information missing in the code or something else ? And how did you guys solve it ? 

 Thank you

**Comment by BaileyJM02** [comment]
It is trying to load data from the hidden `.git` folder you get when you clone a project - I’m guessing you didn’t clone it and you downloaded one of the release files. 

For this to work, the easiest option is to run `git clone <this_repo_url>` and try to run that command again.

**Comment by GohEeEn** [comment]
@BaileyJM02  Sorry for the late reply as I was preparing for my exam. Well actually I did clone it from my project, and I have retried it several time, but it keeps showing the same error as I execute the command here. Is there any possibility that something is missing in the source code?

**Comment by BaileyJM02** [comment]
That’s fine, I was too preparing for exams. Can you please run  `dir /b` within the directory please, this should output all of the folders.

**Comment by GohEeEn** [comment]
It is there when I run `dir /a` command . 
![image](https://user-images.githubusercontent.com/34720382/57973915-24c70480-79a8-11e9-8fbe-b65c77e98f78.png)

**Comment by BaileyJM02** [comment]
Okay, so by the looks of it, the problem is that it isn’t connected to a git repository. I’ll have a look at this now and try to get a fix deployed tonight. 👌 You were correct in saying that it’s an error within the code.

**Comment by GohEeEn** [comment]
@BaileyJM02  thanks a lot ! I will try to figure out the problem as well 😃

**Comment by BaileyJM02** [comment]
Unfortunately, I'm unable to reproduce the error - meaning I can't fix it.

Can you try these things and hopefully this will fix it.
- Check that git if **fully** installed;
- run `bundle install` again;
- run `git init` within the folder;
- add a git user using `git config --global user.name "GohEeEn"`;

Hopefully these will fix the issue.

**Comment by GohEeEn** [comment]
Unfortunately, although I have try all the methods mentioned above,  even try to reinstall related program  and do all the steps in README, it still doesn't work 😓 Actually my repository is saved in my D drive and so all the things were done there as well, will I be a cause of this problem ?

**Comment by GohEeEn** [comment]
For some reason I found that the web page is responsive to the changes on remote source code. Thus, I suppose there is some problem just on the local setup, not the source code itself.

**Comment by GohEeEn** [comment]
@BaileyJM02  Hey I have solve the problem by adding the code `repository : GohEeEn/GohEeEn.github.io` in the _config.yml file, according to the solution provided by  https://github.com/jekyll/jekyll/issues/4705#issuecomment-200991736. 
Thank you for your notice and trying to help 😄 
And all the best in your exam 😉
